config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'

  post '/users/sign_in_as_a_guest', to: 'users#guest'
  post '/users/sign_in_as_an_admin', to: 'users#admin'
  
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  } 
  
  devise_scope :user do
    get 'user/:id', to: 'users/registrations#detail'
    get 'signup', to: 'users/registrations#new'
    get 'login', to: 'users/sessions#new'
    get 'logout', to: 'users/sessions#destroy'
  end
  
  root 'games#index'
  resources :games, only: [:index, :new, :create, :show] do
    resources :comments, only: [:create, :destroy]
  end
  resources :comments, only: [:edit, :update]
  resources :reviews, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :owns, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :conversations do
    resources :messages
  end
  
  # 管理者用ページのルーティング
  namespace :admin do
    root 'games#index'
    resources :games do
      resources :comments, only: [:create, :destroy]
    end
    resources :comments, only: [:index, :edit, :update, :destroy]
    resources :reviews
    resources :owns, only: [:index, :create, :destroy]
    resources :favorites, only: [:index, :create, :destroy]
    resources :users
    resources :relationships, only: [:index, :create, :destroy]
  end
  
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true
  validates :game_id, presence: true
  validates :user_id, presence: true

  belongs_to :game, foreign_key: :game_id
  belongs_to :user, foreign_key: :user_id
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin?
  before_action :set_comment, only: [:edit, :update]

  def index
    @comments = Comment.all
  end

  def create
    @game = Game.find(params[:game_id])
    @comment = @game.comments.build(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        format.js { render :index }
      else
        format.html { render :index, notice: '投稿できませんでした...' }
      end  
    end  
  end  

  def destroy
    @comment = Comment.find_by(id: params[:id], game_id: params[:game_id])
    @comment.destroy
    render :index
  end

  def edit
    respond_to do |format|
      flash.now[:notice] = 'コメントの編集中'
      format.js { render :edit }
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        flash.now[:notice] = 'コメントが編集されました'
        format.js { render :index }
      else
        flash.now[:notice] = 'コメントの編集に失敗しました'
        format.js { render :edit_error }
      end
    end
  end

  private
  
  def comment_params
    params.require(:comment).permit(:body, :game_id, :user_id)
  end  
  
  def set_comment
    @comment = Comment.find(params[:id])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: [:edit, :update]
  before_action -> {restrict_access(@comment.user_id)}, only: [:edit, :update]

  def create
    @game = Game.find(params[:game_id])
    @comment = @game.comments.build(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        format.js { render :index }
      else
        format.html { render :index, notice: '投稿できませんでした...' }
      end
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id], game_id: params[:game_id])
    restrict_access(@comment.user_id)
    @comment.destroy
    render :index
  end

  def edit
    respond_to do |format|
      flash.now[:notice] = 'コメントの編集中'
      format.js { render :edit }
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        flash.now[:notice] = 'コメントが編集されました'
        format.js { render :index }
      else
        flash.now[:notice] = 'コメントの編集に失敗しました'
        format.js { render :edit_error }
      end
    end
  end
  
  private

  def comment_params
    params.require(:comment).permit(:body, :game_id, :user_id)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/comments/_edit.html.erb
<%= form_with(model: [:admin, game, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li> 
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :body, id: "comment_body_#{comment.id}" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/comments/_form.html.erb
<%= form_with(model: [:admin, game, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<!--
  <% if notice %>
    <p class="alert alert-notice"><%= notice %></p>
  <% end %>
-->

  <div class="field">
    <%= form.text_area :body, class: "comment_area", id: "comment_area", placeholder: "新規コメントを入力してください。" %>
  </div>

  <div class="actions">
    <%= form.submit "コメントする", class: "btn btn-primary mr-3" %>
  </div>
<% end %>

app/views/admin/comments/_index.html.erb
<ul>
  <% comments.each do |comment| %>
    <% if comment.id.present? %>
      <li>
        <div class="comment-content" id ="this_comment_<%= comment.id %>"></div>
        <span><%= comment.body %> by <%= link_to comment.user.name, admin_user_path(comment.user_id) %>さん</span>
        <%= link_to "編集", edit_admin_comment_path(comment.id), remote: true, class: "btn btn-primary mr-3" %>
        <%= link_to "削除", admin_game_comment_path(comment.game_id, comment.id), method: :delete, remote: true, class: "btn btn-primary mr-3" %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/admin/comments/edit.js.erb
$("#this_comment_<%= @comment.id %>").replaceWith("<%= j render 'admin/comments/edit', game: @game, comment: @comment %>");

app/views/admin/comments/index.html.erb
<h3>コメント一覧</h3>

<table class="table">
  <tr>
    <th>コメント本文</th>
    <th>コメントしたユーザー</th>
    <th>コメントされたゲームタイトル</th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.body %></td>
    <td><%= link_to "#{comment.user.name}さん", admin_user_path(comment.user_id) %>による</td>
    <td><%= link_to comment.game.title, admin_game_path(comment.game_id) %>へのコメント</td>
  </tr>
<% end %>
</table>

<%= link_to 'トップ画面', admin_root_path, class: "btn btn-primary mr-3" %>

app/views/admin/comments/index.js.erb
$("#comments_area").html("<%= j(render 'admin/comments/index', { comments: @comment.game.comments, game: @comment.game, user: @comment.user }) %>")
$("textarea").val('')