config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'

  post '/users/sign_in_as_a_guest', to: 'users#guest'
  post '/users/sign_in_as_an_admin', to: 'users#admin'
  
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  } 
  
  devise_scope :user do
    get 'user/:id', to: 'users/registrations#detail'
    get 'signup', to: 'users/registrations#new'
    get 'login', to: 'users/sessions#new'
    get 'logout', to: 'users/sessions#destroy'
  end
  
  root 'games#index'
  resources :games, only: [:index, :new, :create, :show] do
    resources :comments, only: [:create, :destroy]
  end
  resources :comments, only: [:edit, :update]
  resources :reviews, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :owns, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :conversations do
    resources :messages
  end
  
  # 管理者用ページのルーティング
  namespace :admin do
    root 'games#index'
    resources :games do
      resources :comments, only: [:create, :destroy]
    end
    resources :comments, only: [:index, :edit, :update, :destroy]
    resources :reviews
    resources :owns, only: [:index, :create, :destroy]
    resources :favorites, only: [:index, :create, :destroy]
    resources :users
    resources :relationships, only: [:index, :create, :destroy]
  end
  
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :admin?
  
  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
  end
  
  def create
    @review = current_user.reviews.build(review_params)
    if params[:back]
      render :new
    else
      if @review.save
        redirect_to admin_review_path(@review.id), notice: "レビューを作成しました！"
      else
        render :new
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to admin_review_path(@review), notice: "レビューを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @review.destroy
    redirect_to admin_reviews_path, notice:"レビューを削除しました！"
  end

  private

  def review_params
    params.require(:review).permit(:direction, :operability, :story, :volume, :like, :summary, :body, :game_id, :user_id)
  end

  def set_review
    @review = Review.find(params[:id])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action -> {restrict_access(@review.user_id)}, only: [:edit, :update, :destroy]
  
  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
  end
  
  def create
    @review = current_user.reviews.build(review_params)
    if params[:back]
      render :new
    else
      if @review.save
        # @review.game.favorites.each do |favorite|
        #   ReviewMailer.inform_mail(@review, favorite.user).deliver
        # end

        # @review.user.follower.each do |follower|
        #   ReviewMailer.inform_mail(@review, follower).deliver
        # end
        redirect_to review_path(@review.id), notice: "レビューありがとうございます！！"
      else
        render :new
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to review_path(@review.id), notice: "レビューを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @review.destroy
    redirect_to user_path(@review.user_id), notice:"レビューを削除しました！"
  end

  private

  def review_params
    params.require(:review).permit(:direction, :operability, :story, :volume, :like, :summary, :body, :game_id, :user_id)
  end

  def set_review
    @review = Review.find(params[:id])
  end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/admin/reviews/_form.html.erb
<%= form_with(model: [:admin, @review], local: true) do |form| %>

  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h3><%= @review.errors.count %>件のエラーがあります。</h3>
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="filed">
    <%= form.label :game_id, "ゲームタイトル" %> : 
    <%= form.collection_select :game_id, Game.all, :id, :title, {selected: @review.game_id}%>
  </div>

  <%= link_to "レビューしたいゲームがない場合...", new_admin_game_path %>

  <div class="field">
    <%= form.label :direction %> : 
    <%= form.number_field :direction, min: 0, max: 20 %>
  </div>

  <div class="field">
    <%= form.label :operability %> : 
    <%= form.number_field :operability, min: 0, max: 20 %>
  </div>

  <div class="field">
    <%= form.label :story %> : 
    <%= form.number_field :story, min: 0, max: 20 %>
  </div>

  <div class="field">
    <%= form.label :volume %> : 
    <%= form.number_field :volume, min: 0, max: 20 %>
  </div>

  <div class="field">
    <%= form.label :like %> : 
    <%= form.number_field :like, min: 0, max: 20 %>
  </div>

  <div class="field">
    <%= form.label :summary %> : 
    <%= form.text_field :summary %>
  </div>

  <div class="field">
    <div><%= form.label :body %></div>
    <div><%= form.text_area :body %></div>
  </div>

  <div class="action field">
    <%= form.submit class: "btn btn-primary mr-3" %>
  </div>

<% end %>

<%= link_to "レビュー一覧", admin_reviews_path, class: "btn btn-primary mr-3" %>

app/views/admin/reviews/edit.html.erb
<h3>レビュー編集</h3>

<%= render 'form' %>

app/views/admin/reviews/index.html.erb
<h3>レビュー一覧</h3>

<table class="table">
  <tr>
    <th>要約</th>
    <th>レビューしたユーザー</th>
    <th>レビューされたゲームタイトル</th>
    <th>レビュー総合点</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @reviews.each do |review| %>
    <tr>
      <td><%= review.summary %></td>
      <td><%= link_to review.user.name, admin_user_path(review.user_id) %>さんによる</td>
      <td><%= link_to review.game.title, admin_game_path(review.game_id) %>へのレビュー</td>
      <td><%= review.direction + review.direction + review.operability + review.story + review.volume %>点</td>
      <td><%= link_to "詳細", admin_review_path(review.id), class: "btn btn-primary mr-3" %></td>
      <td><%= link_to "編集", edit_admin_review_path(review.id), class: "btn btn-primary mr-3" %></td>
      <td><%= link_to '削除', admin_review_path(review.id), method: :delete ,data: { confirm: '本当に削除していいですか？' }, class: "btn btn-primary mr-3" %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'トップ画面', admin_root_path, class: "btn btn-primary mr-3"  %>
<%= link_to '新規レビュー投稿', new_admin_review_path, class: "btn btn-primary mr-3" %>

app/views/admin/reviews/new.html.erb
<h3>新規レビュー投稿</h3>

<%= render 'form' %>

app/views/admin/reviews/show.html.erb
<h3><%= @review.summary %></h3>
<h4><%= link_to @review.user.name, admin_user_path(@review.user_id) %>さんによる<%= link_to @review.game.title, admin_game_path(@review.game_id) %>へのレビュー</h4>

<p><strong>グラフィック・サウンド: </strong><%= @review.direction %>点/20点</p>
<p><strong>操作性: </strong><%= @review.operability %>点/20点</p>
<p><strong>ストーリー・世界観: </strong><%= @review.story %>点/20点</p>
<p><strong>ゲームボリューム: </strong><%= @review.volume %>点/20点</p>
<p><strong>ハマり度: </strong><%= @review.like %>点/20点</p>
<p><strong>総合点: </strong><%= @review.direction + @review.operability + @review.story + @review.volume + @review.like %>点/100点</p>
<p><strong>コメント: </strong><%= @review.body %></p>

<%= link_to '編集', edit_admin_review_path(@review.id), class: "btn btn-primary mr-3" %>
<%= link_to '削除', edit_admin_review_path(@review.id), method: :delete ,data: { confirm: '本当に削除していいですか？' }, class: "btn btn-primary mr-3" %>