config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'

  post '/users/sign_in_as_a_guest', to: 'users#guest'
  post '/users/sign_in_as_an_admin', to: 'users#admin'
  
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  } 
  
  devise_scope :user do
    get 'user/:id', to: 'users/registrations#detail'
    get 'signup', to: 'users/registrations#new'
    get 'login', to: 'users/sessions#new'
    get 'logout', to: 'users/sessions#destroy'
  end
  
  root 'games#index'
  resources :games, only: [:index, :new, :create, :show] do
    resources :comments, only: [:create, :destroy]
  end
  resources :comments, only: [:edit, :update]
  resources :reviews, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :owns, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :conversations do
    resources :messages
  end
  
  # 管理者用ページのルーティング
  namespace :admin do
    root 'games#index'
    resources :games do
      resources :comments, only: [:create, :destroy]
    end
    resources :comments, only: [:index, :edit, :update, :destroy]
    resources :reviews
    resources :owns, only: [:index, :create, :destroy]
    resources :favorites, only: [:index, :create, :destroy]
    resources :users
    resources :relationships, only: [:index, :create, :destroy]
  end
  
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
end

app/models/game.rb
class Game < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :company, presence: true
  validates :genre, presence: true
  validates :price, presence: true, numericality: { only_integer: true }

  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :own_users, through: :owns, source: :user
  
  has_many :owns, dependent: :destroy
  has_many :own_users, through: :owns, source: :user

  enum genre: { action: 1, action_RPG: 2, RPG: 3, adventure: 4, action_adventure: 5, shouting: 6, FPS_TPS: 7, 
                pazzle: 8, simulation: 9, racing: 10, music: 11, battle: 12, sports: 13, other: 14 
              }

  scope :recent, -> { order(id: :desc).limit(5) }
  
  # ransacker :direction_score do
  #   query = '(SELECT AVG(reviews.direction) FROM reviews WHERE reviews.game_id = game.id GROUP BY reviews.game_id)'
  #   Arel.sql(query)
  # end

  # ransacker :reviews_count do
  #   query = '(SELECT AVG(reviews.direction) FROM reviews WHERE reviews.game_id = game.id GROUP BY reviews.game_id)'
  #   Arel.sql(query)
  # end

  # COLUMN_NAME_SEARCH_MAP = {
  #   "a" => [1],
  #   "b" => [2,3],
  #   "c" => [4,5]
  # }

  # ransacker :column_name_search, formatter: proc { |v| COLUMN_NAME_SEARCH_MAP[v.to_sym] } do |parent|
  #   parent.table[:column_name]
  # end
  
  mount_uploader :icon, IconUploader
end

app/controllers/admin/games_controller.rb
class Admin::GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :admin?
  
  def index
    # binding.pry

    unless params[:q].nil?
      if params[:q][:price_gteq].present? && params[:q][:price_lt].present?
        if params[:q][:price_gteq] > params[:q][:price_lt]
          flash[:notice] = "価格範囲の下限が上限を上回っています。"
          redirect_to games_path
        end
      end

      if params[:q][:released_at_gteq].present? && params[:q][:released_at_lteq].present?
        if params[:q][:released_at_gteq].to_time > params[:q][:released_at_lteq].to_time
        flash[:notice] = "発売日の下限が上限より後日になっています。"
          redirect_to games_path
        end
      end
    end

    @q = Game.ransack(params[:q])
    if params[:order_by_direction] # 演出点数順（降順）
      @games = Game.select('games.*', 'sum(reviews.direction) * 5 / count(reviews.id) AS reviews').left_joins(:reviews).group('games.id').order('reviews desc').page(params[:page]).per(100)
      params.delete("order_by_direction")
    elsif params[:order_by_operability] # 操作性点数順（降順）
      @games = Game.select('games.*', 'sum(reviews.operability) * 5 / count(reviews.id) AS reviews').left_joins(:reviews).group('games.id').order('reviews desc').page(params[:page]).per(100)
      params.delete("order_by_operability")
    elsif params[:order_by_story] # ストーリー点数順（降順）
      @games = Game.select('games.*', 'sum(reviews.story) * 5 / count(reviews.id) AS reviews').left_joins(:reviews).group('games.id').order('reviews desc').page(params[:page]).per(100)
      params.delete("order_by_story")
    elsif params[:order_by_volume] # ボリューム点数順（降順）
      @games = Game.select('games.*', 'sum(reviews.volume) * 5 / count(reviews.id) AS reviews').left_joins(:reviews).group('games.id').order('reviews desc').page(params[:page]).per(100)
      params.delete("order_by_volume")
    elsif params[:order_by_like] # ハマり度点数順（降順）
      @games = Game.select('games.*', 'sum(reviews.like) * 5 / count(reviews.id) AS reviews').left_joins(:reviews).group('games.id').order('reviews desc').page(params[:page]).per(100)
      params.delete("order_by_like")
    elsif params[:order_by_sum] # 合計点数順（降順）
      @games = Game.select('games.*', '(sum(reviews.direction) + sum(reviews.operability) + sum(reviews.story) + sum(reviews.volume) + sum(reviews.like)) / count(reviews.id) AS reviews')
      .left_joins(:reviews).group('games.id').order('reviews desc').page(params[:page]).per(100)
      params.delete("order_by_sum")
    elsif params[:order_by_reviews] # レビュー個数順（降順）
      @games = Game.select('games.*', 'count(reviews.id) AS reviews').left_joins(:reviews).group('games.id').order('reviews desc').page(params[:page]).per(100)
      params.delete("order_by_reviews")
    else # 追加順（デフォルト、降順）
      @q.sorts = 'created_at desc' if @q.sorts.empty?
      @games = @q.result(distinct: true).page(params[:page]).per(10)
    end
  end
  
  def new
    @game = Game.new
  end
  
  def create
    @game = Game.new(game_params)
    if params[:back]
      render :new
    else
      if @game.save
        redirect_to admin_game_path(@game.id), notice: "ゲームを作成しました！"
      else
        render :new
      end
    end
  end

  def show
    @comments = @game.comments
    @comment = @game.comments.build
    @favorite = current_user.favorites.find_by(game_id: @game.id)
    @own = current_user.owns.find_by(game_id: @game.id)
  end

  def edit
  end

  def update
    if @game.update(game_params)
      redirect_to admin_game_path(@game.id), notice: "ゲームを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @game.destroy
    redirect_to admin_games_path, notice:"ゲームを削除しました！"
  end

  private

  def game_params
    params.require(:game).permit(:title, :company, :genre, :price, :released_at, :story, :icon, :icon_cache)
  end

  def search_params
    params.require(:q).permit(:title_or_company_cont, :price_gteq, :price_lt, :genre_eq, :released_at_gteq, :released_at_lteq)
  end

  def set_game
    @game = Game.find(params[:id])
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_game, only: [:show]
  
  def index
    unless params[:q].nil?
      if params[:q][:price_gteq].present? && params[:q][:price_lt].present?
        if params[:q][:price_gteq] > params[:q][:price_lt]
          flash[:notice] = "価格の検索範囲を正しく入力してください。"
          redirect_to games_path
        end
      end

      if params[:q][:released_at_gteq].present? && params[:q][:released_at_lteq].present?
        if params[:q][:released_at_gteq].to_time > params[:q][:released_at_lteq].to_time
        flash[:notice] = "発売日の検索範囲を正しく入力してください。"
          redirect_to games_path
        end
      end
    end

    @q = Game.ransack(params[:q])
    if params[:order_by_direction] # 演出点数順（降順）
      @games = Game.select('games.*', 'sum(reviews.direction) * 5 / count(reviews.id) AS reviews').left_joins(:reviews).group('games.id').order('reviews desc').page(params[:page]).per(100)
      params.delete("order_by_direction")
    elsif params[:order_by_operability] # 操作性点数順（降順）
      @games = Game.select('games.*', 'sum(reviews.operability) * 5 / count(reviews.id) AS reviews').left_joins(:reviews).group('games.id').order('reviews desc').page(params[:page]).per(100)
      params.delete("order_by_operability")
    elsif params[:order_by_story] # ストーリー点数順（降順）
      @games = Game.select('games.*', 'sum(reviews.story) * 5 / count(reviews.id) AS reviews').left_joins(:reviews).group('games.id').order('reviews desc').page(params[:page]).per(100)
      params.delete("order_by_story")
    elsif params[:order_by_volume] # ボリューム点数順（降順）
      @games = Game.select('games.*', 'sum(reviews.volume) * 5 / count(reviews.id) AS reviews').left_joins(:reviews).group('games.id').order('reviews desc').page(params[:page]).per(100)
      params.delete("order_by_volume")
    elsif params[:order_by_like] # ハマり度点数順（降順）
      @games = Game.select('games.*', 'sum(reviews.like) * 5 / count(reviews.id) AS reviews').left_joins(:reviews).group('games.id').order('reviews desc').page(params[:page]).per(100)
      params.delete("order_by_like")
    elsif params[:order_by_sum] # 合計点数順（降順）
      @games = Game.select('games.*', '(sum(reviews.direction) + sum(reviews.operability) + sum(reviews.story) + sum(reviews.volume) + sum(reviews.like)) / count(reviews.id) AS reviews')
      .left_joins(:reviews).group('games.id').order('reviews desc').page(params[:page]).per(100)
      params.delete("order_by_sum")
    elsif params[:order_by_reviews] # レビュー個数順（降順）
      @games = Game.select('games.*', 'count(reviews.id) AS reviews').left_joins(:reviews).group('games.id').order('reviews desc').page(params[:page]).per(100)
      params.delete("order_by_reviews")
    else # 追加順（デフォルト、降順）
      @q.sorts = 'created_at desc' if @q.sorts.empty?
      @games = @q.result(distinct: true).page(params[:page]).per(10)
    end
  end
  
  def new
    @game = Game.new
  end
  
  def create
    @game = Game.new(game_params)
    if params[:back]
      render :new
    else
      if @game.save
        redirect_to game_path(@game.id), notice: "ゲームを作成しました！"
      else
        render :new
      end
    end
  end

  def show
    @comments = @game.comments
    @comment = @game.comments.build
    @favorite = current_user.favorites.find_by(game_id: @game.id)
    @own = current_user.owns.find_by(game_id: @game.id)
  end

  private

  def game_params
    params.require(:game).permit(:title, :company, :genre, :price, :released_at, :story, :icon, :icon_cache)
  end

  def search_params
    params.require(:q).permit(:title_or_company_cont, :price_gteq, :price_lt, :genre_eq, :released_at_gteq, :released_at_lteq)
  end

  def set_game
    @game = Game.find(params[:id])
  end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/admin/games/_form.html.erb
<%= form_with(model: [:admin, @game], local: true) do |form| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h3><%= @game.errors.count %>件のエラーがあります。</h3>
      <ul>
        <% @game.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %> : 
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :company %> : 
    <%= form.text_field :company %>
  </div>
      
  <div class="field">
    <%= form.label :genre %> : 
    <%= form.select :genre, Game.genres.keys.map {|k| [I18n.t("enums.game.genre.#{k}"), k]} %>
  </div>
  
  <div class="field">
    <%= form.label :price %> : 
    <%= form.number_field :price, min: 0, max: 100000 %>円
  </div>
  
  <div class="field">
    <%= form.label :released_at %> : 
    <%= form.date_select :released_at %>
  </div>
  
  <div class="field">
    <div><%= form.label :story %></div>
    <div><%= form.text_area :story %></div>
  </div>
  
  <div class="field">
    <%= form.label :icon %>
    <%= form.file_field :icon, class: "icon_file" %>
    <%= image_tag(@game.icon.resize_for_game_icon.url) if @game.icon && @game.icon.url %>
    <%= form.hidden_field :icon_cache %>
  </div>

  <div class="action field">
    <%= form.submit class: "btn btn-primary mr-3" %>
  </div>

<% end %>

<%= link_to "ゲーム一覧", admin_games_path, class: "btn btn-primary mr-3" %>

app/views/admin/games/edit.html.erb
<h3>ゲーム編集</h3>

<%= render 'form' %>

<%= link_to '詳細へ', admin_game_path(@game.id), class: "btn btn-primary mr-3" %>

app/views/admin/games/index.html.erb
<%= search_form_for @q do |form| %>
  <div class="form-inline">
    <div class="form-group">
      <%= form.label :title_or_company, "タイトルまたは販売会社" %> : 
      <%= form.search_field :title_or_company_cont, include_blank: true, class: "search_title_or_company_form form-control" %>, 
    </div>

    <div class="form-group">
      <%= form.label :price, class: 'form-group' %> : 
      <%= form.number_field :price_gteq, min: 0, include_blank: true, class: 'form-control' %>以上〜
      <%= form.number_field :price_lt, min: 0, max: 100000, include_blank: true, class: 'form-control' %>未満
    </div>

    <br>

    <div class="form-group">
      <%= form.label :genre, class: 'form-group' %> : 
      <%= form.select :genre_eq, Game.genres.map {|k, v| [Game.genres_i18n[k], v]}, include_blank: true, class: 'form-control' %>, 
    </div>
    
    <div class="form-group">
      <%= form.label :released_at, class: 'form-group' %> : 
      <%= form.date_field :released_at_gteq, include_blank: true, class: 'form-control' %>〜
      <%= form.date_field :released_at_lteq, include_blank: true, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.submit "検索", class: 'btn btn-primary' %>
      <%= link_to 'クリア', admin_games_path, class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

<table class="table">
  <tr>
    <th class="display_center"><%= sort_link(@q, :title, "タイトル名", default_order: :asc) %></th>
    <th class="display_center"><%= sort_link(@q, :company, "販売会社", default_order: :asc) %></th>
    <th class="display_center"><%= sort_link(@q, :released_at, "発売日", default_order: :desc) %></th>

    <th class="display_center"><%= link_to admin_games_path(order_by_direction: true) do %>グラフィック<br>・サウンド<% end %></th>
    <th class="display_center"><%= link_to admin_games_path(order_by_operability: true) do %>操作性<br>・ロード<% end %></th>
    <th class="display_center"><%= link_to admin_games_path(order_by_story: true) do %>ストーリー<br>・世界観<% end %></th>
    <th class="display_center"><%= link_to admin_games_path(order_by_volume: true) do %>ボリューム・<br>やりこみ要素<% end %></th>
    <th class="display_center"><%= link_to "ハマり度", admin_games_path(order_by_like: true) %></th>
    <th class="display_center"><%= link_to "総合点数", admin_games_path(order_by_sum: true) %></th>
    <th class="display_center"><%= link_to "レビュー件数", admin_games_path(order_by_reviews: true) %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @games.each do |game| %>
    <tr>
      <td colspan="2"><%= image_tag(game.icon.resize_for_game_icon.url) if game.icon && game.icon.url %><br><strong><%= game.title %></strong><br>from <%= game.company %></td>
      <td class="display_center"><%= game.released_at %></td>
      <td class="display_center"><%= game.reviews.sum(:direction) * 5 / game.reviews.count if game.reviews.present? %><% if game.reviews.present? %>点<% end %></td>
      <td class="display_center"><%= game.reviews.sum(:operability) * 5 / game.reviews.count if game.reviews.present? %><% if game.reviews.present? %>点<% end %></td>
      <td class="display_center"><%= game.reviews.sum(:story) * 5 / game.reviews.count if game.reviews.present? %><% if game.reviews.present? %>点<% end %></td>
      <td class="display_center"><%= game.reviews.sum(:volume) * 5 / game.reviews.count if game.reviews.present? %><% if game.reviews.present? %>点<% end %></td></td>
      <td class="display_center"><%= game.reviews.sum(:like) * 5 / game.reviews.count if game.reviews.present? %><% if game.reviews.present? %>点<% end %></td></td>
      <td class="display_center"><%= (game.reviews.sum(:direction) + game.reviews.sum(:operability) + game.reviews.sum(:story) + game.reviews.sum(:volume) + game.reviews.sum(:like)) / game.reviews.count if game.reviews.present? %><% if game.reviews.present? %>点<% end %></td></td>
      <td class="display_center"><%= game.reviews.count %>件</td>
      <td class="display_center"><%= link_to "詳細", admin_game_path(game.id), class: "btn btn-primary mr-3" %></td>
      <td class="display_center"><%= link_to "編集", edit_admin_game_path(game.id), class: "btn btn-primary mr-3" %></td>
      <td class="display_center"><%= link_to "削除", admin_game_path(game.id), method: :delete ,data: { confirm: '本当に削除していいですか？' }, class: "btn btn-primary mr-3" %></td>
    </tr>
  <% end %>
</table>

<%= paginate @games %>

app/views/admin/games/show.html.erb
<h3><%= @game.title%>の詳細</h3>

<p><strong>ID : </strong><%= @game.id %></p>
<p><strong>タイトル : </strong><%= @game.title %></p>
<p><strong>制作会社 : </strong><%= @game.company %></p>
<p><strong>ジャンル : </strong><%= @game.genre_i18n %></p>
<p><strong>価格 : </strong><%= @game.price %>円</p> 
<p><strong>発売日 : </strong><%= @game.released_at %></p>
<p class="game_story"><strong>あらすじ<br></strong><%= @game.story %></p>
<p><strong>パッケージ</strong><br><%= image_tag(@game.icon.resize_for_game_icon.url) if @game.icon && @game.icon.url %></p>

<%= link_to 'ゲーム一覧', admin_games_path, class: "btn btn-primary mr-3" %>
<%= link_to '編集', edit_admin_game_path(@game.id), class: "btn btn-primary mr-3" %>
<%= link_to '削除', admin_game_path(@game.id), method: :delete ,data: { confirm: '本当に削除していいですか？' }, class: "btn btn-primary mr-3" %>

<% if @favorite.present? %>
  <%= link_to '気になるを解除する', admin_favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
<% else %>
  <%= link_to '気になる登録', admin_favorites_path(game_id: @game.id), method: :post, class: 'btn btn-primary' %>
<% end %>

<% if @own.present? %>
  <%= link_to '持ってるを解除する', admin_own_path(id: @own.id), method: :delete, class: 'btn btn-danger' %>
<% else %>
  <%= link_to '持ってる登録', admin_owns_path(game_id: @game.id), method: :post, class: 'btn btn-primary' %>
<% end %>

<h4><%= @game.title%>に対する<%= @game.reviews.count %>件のレビュー</h4>
<table class="table">
  <tr>
    <th>レビューしたユーザー</th>
    <th>一言</th>
    <th>レビュー総合点</th>
  </tr>

<% @game.reviews.each do |review| %>
  <tr>
    <td><%= link_to review.user.name, admin_user_path(review.user_id) %>さんによる</td>
    <td><%= review.summary %></td>
    <td><%= review.direction + review.direction + review.operability + review.story + review.volume %>点</td>
    <td><%= link_to "詳細", admin_review_path(review.id), class: 'btn btn-primary' %></td>
    <td><%= link_to "詳細", edit_admin_review_path(review.id), class: 'btn btn-primary' %></td>
    <td><%= link_to "削除", admin_review_path(review.id), method: :delete, class: 'btn btn-primary',data: { confirm: '本当に削除していいですか？' } %></td>
  </tr>
<% end %>
</table>

<h4><%= @game.title %>に対するコメント・質問</h4>
<div id="comments_area">
  <%= render partial: 'admin/comments/index', locals: { comments: @comments, game: @game, user: current_user } %>
</div>
<%= render partial: 'admin/comments/form', locals: { comment: @comment, game: @game, user: current_user } %>

<%= link_to 'トップ画面', admin_games_path, class: "btn btn-primary mr-3" %>