config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'

  post '/users/sign_in_as_a_guest', to: 'users#guest'
  post '/users/sign_in_as_an_admin', to: 'users#admin'
  
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  } 
  
  devise_scope :user do
    get 'user/:id', to: 'users/registrations#detail'
    get 'signup', to: 'users/registrations#new'
    get 'login', to: 'users/sessions#new'
    get 'logout', to: 'users/sessions#destroy'
  end
  
  root 'games#index'
  resources :games, only: [:index, :new, :create, :show] do
    resources :comments, only: [:create, :destroy]
  end
  resources :comments, only: [:edit, :update]
  resources :reviews, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :owns, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :conversations do
    resources :messages
  end
  
  # 管理者用ページのルーティング
  namespace :admin do
    root 'games#index'
    resources :games do
      resources :comments, only: [:create, :destroy]
    end
    resources :comments, only: [:index, :edit, :update, :destroy]
    resources :reviews
    resources :owns, only: [:index, :create, :destroy]
    resources :favorites, only: [:index, :create, :destroy]
    resources :users
    resources :relationships, only: [:index, :create, :destroy]
  end
  
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :owns, dependent: :destroy

  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :trackable, :validatable
  # , :confirmable

  mount_uploader :icon, IconUploader

  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end
  
  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user) #フォローしているかどうかを確認する
    active_relationships.find_by(followed_id: other_user.id)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :show, :edit, :update, :destroy]
  before_action :admin?
  
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if params[:back]
      render :new
    else
      if @user.save
        redirect_to admin_user_path(@user.id), notice: "ユーザーを作成しました！"
      else
        render :new
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id), notice: "ユーザーを編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to new_user_registration_path, notice:"ユーザーを削除しました。"
  end

  def guest
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
    sign_in user
    redirect_to admin_root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  def admin
    user = User.find_or_create_by!(email: 'admin@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
    sign_in user
    redirect_to admin_root_path, notice: '管理者ユーザーとしてログインしました。'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :introduce, :icon, :icon_cache)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end
  
  # DELETE /resource
  def destroy
    super
  end
  
  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end
  
  protected
  
  def detail
    @user = User.find_by(id: params[:id])
  end
  
  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    "/users/#{current_user.id}"
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
  
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy]  
  before_action -> {restrict_access(@user.id)}, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if params[:back]
      render :new
    else
      if @user.save
        redirect_to user_path(@user.id), notice: "ユーザー登録しました！"
      else
        render :new
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "ユーザー情報を編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to new_user_registration_path, notice:"ユーザーを削除しました。"
  end

  def guest
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  def admin
    user = User.find_or_create_by!(email: 'admin@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
    sign_in user
    redirect_to admin_root_path, notice: '管理者ユーザーとしてログインしました。'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :introduce, :icon, :icon_cache)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_follow_form.html.erb
<div id="follow_form_<%= @user.id %>">
  <% unless current_user.following?(@user) %>
    <%= form_with(model: current_user.active_relationships.build(followed_id: @user.id)) do |f| %>
      <%= f.hidden_field :followed_id %>
      <%= f.submit "フォロー", class: "btn btn-primary mr-3" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id), method: :delete ) do |f| %>
      <%= f.submit "フォロー解除", class: "btn btn-primary mr-3" %>
    <% end %>
  <% end %>
</div>

app/views/admin/users/edit.html.erb
<h3>ユーザー情報編集</h3>

<%= form_with(model: [:admin, @user], local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h3><%= @user.errors.count %>件のエラーがあります。</h3>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %> : 
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %> : 
    <%= form.text_field :email %>
  </div>
          
  <div class="field">
    <%= form.label :introduce %> : 
    <%= form.text_field :introduce %>
  </div>
  
  <div class="field">
    <%= form.label :icon %> : 
    <%= form.file_field :icon, class: "icon_file" %>
    <%= image_tag(@user.icon.resize_for_user_icon.url) if @user.icon && @user.icon.url %>
    <%= form.hidden_field :icon_cache %>
  </div>

  <div class="field">
    <%= form.label :admin %> : 
    <%= form.check_box :admin %>
  </div>

  <div class="action">
    <%= form.submit class: "btn btn-primary mr-3" %>
  </div>

<% end %>

<%= link_to "ユーザー一覧", admin_users_path, class: "btn btn-primary mr-3" %>

app/views/admin/users/index.html.erb
<h3>ユーザー一覧</h3>

<table class="table">
  <tr>
    <th>アイコン</th>
    <th>ID</th>
    <th>ユーザーネーム</th>
    <th colspan="3"></th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= image_tag(user.icon.resize_for_user_icon.url) if user.icon && user.icon.url %></td>
      <td><%= user.id %></td>
      <td><%= user.name %></td>
      <td><%= link_to '詳細', admin_user_path(user), class: "btn btn-primary mr-3" %></td>
      <td><%= link_to '編集', edit_admin_user_path(user), class: "btn btn-primary mr-3" %></td>
      <td><%= link_to '削除', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary mr-3" %></td>
    </tr>
  <% end %>
</table>

app/views/admin/users/new.html.erb
<h3>新規ユーザー登録</h3>

<%= form_with(model: [:admin, @user], local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h3><%= @user.errors.count %>件のエラーがあります。</h3>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %> : 
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %> : 
    <%= form.text_field :email %>
  </div>
      
  <div class="field">
    <%= form.label :password %> : 
    <%= form.text_field :password %>
  </div>
  
  <div class="action">
    <%= form.submit class: "btn btn-primary mr-3" %>
  </div>

<% end %>

<%= link_to "ユーザー一覧", admin_users_path %>

app/views/admin/users/show.html.erb
<h3><%= @user.name %>の詳細</h3>

<p><strong>ID : </strong><%= @user.id %></p>
<p><strong>名前 : </strong><%= @user.name %></p>
<p><strong>フォロー : </strong><%= @user.following.count %>人 / <strong>フォロワー : </strong><%= @user.followers.count %>人</p>
<p><strong>メールアドレス : </strong><%= @user.email %></p>
<p><strong>管理者権限 : </strong><%= @user.admin %></p>
<p class="user_introduce"><strong>自己紹介文</strong><br><%= @user.introduce %></p> 
<p><strong>アイコン</strong><br><%= image_tag(@user.icon.resize_for_user_icon.url) if @user.icon && @user.icon.url %></p>

<% if @user != current_user %>
  <%= render 'follow_form', user: @user %>
  <%= link_to 'メッセージ', conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: :post, class: "btn btn-primary mr-3" %>
<% end %>
<%= link_to 'プロフィール編集', edit_admin_user_path(@user.id), class: "btn btn-primary mr-3" %>
<%= link_to '強制退会', admin_user_path(@user.id), method: :delete, class: "btn btn-primary mr-3" ,data: { confirm: '本当にアカウント削除していいですか？（ゲストアドミンユーザーでログインの場合はご遠慮ください。）' } %>
<%= link_to 'ユーザー一覧', admin_users_path, class: "btn btn-primary mr-3" %>

<% if @user.reviews.present? %>
  <p><%= @user.name %>さんが投稿したゲームレビュー一覧</p>
  <table class="table">
    <tr>
      <th>一言</th>
      <th>レビューしたゲームタイトル</th>
      <th>総合点</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <% @user.reviews.each do |review| %>
      <tr class="review_row">
        <td><%= review.summary %></th>
        <td><%= link_to review.game.title, admin_game_path(review.game_id) %>へのレビュー</td>
        <td><%= review.direction + review.direction + review.operability + review.story + review.volume %>点</td>
        <td><%= link_to "詳細", admin_review_path(review.id), class: "btn btn-primary mr-3" %></td>
        <td><%= link_to "編集", edit_admin_review_path(review.id), class: "btn btn-primary mr-3" %></td>
        <td><%= link_to '削除', admin_review_path(review.id), method: :delete, data: { confirm: '本当に削除していいですか？' }, class: "btn btn-primary mr-3" %></td>
      </tr>
    <% end %>
  </table>
<% end %>

<% if @user.favorites.present? %>
  <p><%= @user.name %>さんの気になっているゲーム一覧</p>
  <table class="table">
    <tr>
      <th>パッケージ</th>
      <th>ゲームタイトル</th>
      <th>販売会社</th>
    </tr>

    <% @user.favorites.each do |favorite| %>
      <tr class="favorite_row">
        <td><%= image_tag(favorite.game.icon.resize_for_game_icon.url) if favorite.game.icon && favorite.game.icon.url %></td>
        <td><%= link_to favorite.game.title, admin_game_path(favorite.game_id) %></th>
        <td><%= favorite.game.company %></td>
      </tr>
    <% end %>
  </table>
<% end %>

<% if @user.owns.present? %>
  <p><%= @user.name %>さんの持っているゲーム一覧</p>
  <table class="table">
    <tr>
      <th>パッケージ</th>
      <th>ゲームタイトル</th>
      <th>販売会社</th>
    </tr>

    <% @user.owns.each do |own| %>
      <tr class="own_row">
        <td><%= image_tag(own.game.icon.resize_for_game_icon.url) if own.game.icon && own.game.icon.url %></td>
        <td><%= link_to own.game.title, admin_game_path(own.game_id) %></th>
        <td><%= own.game.company %></td>
      </tr>
    <% end %>
  </table>
<% end %>

<% if @user.following.present? %>
  <p><%= @user.following.count %>人のフォロー</p>
    <% @user.following.each do |follow| %>
      <%= image_tag(follow.icon.resize_for_game_icon.url) if follow.icon && follow.icon.url %>
      <%= link_to follow.name, admin_user_path(follow.id) %>
    <% end %>
<% end %>

<% if @user.followers.present? %>
  <p><%= @user.followers.count %>人のフォロワー</p>
    <% @user.followers.each do |follower| %>
      <%= image_tag(follower.icon.resize_for_game_icon.url) if follower.icon && follower.icon.url %>
      <%= link_to follower.name, admin_user_path(follower.id) %>
    <% end %>
<% end %>  